### ISSUE TITLE
problem running version 3.4

### ISSUE THREAD

**Issue by wouterse** [klejejs/python-thermia-online-api#13]
After downloading, the latest version (3.4) the api stopped working for my code. Running the example gives the same error:

Traceback (most recent call last):
  File "example.py", line 2, in <module>
    from ThermiaOnlineAPI import Thermia
  File "/home/pi/python-thermia-online-api-main-4/ThermiaOnlineAPI/__init__.py", line 3, in <module>
    from ThermiaOnlineAPI.api.ThermiaAPI import ThermiaAPI
  File "/home/pi/python-thermia-online-api-main-4/ThermiaOnlineAPI/api/ThermiaAPI.py", line 28, in <module>
    from ..model.HeatPump import ThermiaHeatPump
  File "/home/pi/python-thermia-online-api-main-4/ThermiaOnlineAPI/model/HeatPump.py", line 41, in <module>
    "hot_water_boost_switch": None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by klejejs** [comment]
Hmm, this is a weird error. Which Python version are you using?

**Comment by wouterse** [comment]
I'm running Python 3.7.3 (default, Jul 25 2020, 13:03:44), the api version that I downloaded 23/12 did not have this problem.

**Comment by klejejs** [comment]
Sorry for the error, it was my mistake. In the latest release, I added typings for some variables and functions but did not think about how that syntax would affect older Python versions. It turns out the syntax was supported only by Python 3.10 and newer.
The new release `3.5` has the issue fixed.

**Comment by wouterse** [comment]
Thanks for your quick fix!
